
os: linux
language: php

services:
  - docker

env:
  global:
    - DOCKER_COMPOSE_VERSION=1.17.1
  matrix:
    - DRUPAL_VERSION=8.8.x-dev

before_install:
  - docker-compose up --detach
  - docker ps

install:
  - docker-compose exec --user root php composer require drupal/core-recommended:$DRUPAL_VERSION --dev --prefer-dist

before_script:
  - docker-compose exec --user root php ./vendor/bin/run drupal:site-setup
  - docker-compose exec --user root php ./vendor/bin/run drupal:site-install
  - docker-compose exec --user root php chown -R www-data:www-data build

script:
  - docker-compose exec --user root php ./vendor/bin/grumphp run
  - docker-compose exec --user root php ./vendor/bin/phpunit
  - docker-compose exec --user root php ./vendor/bin/behat --config behat-$DRUPAL_VERSION.yml

notifications:
  email: false
